### ISSUE TITLE
Criteo用的是全部数据吗

### ISSUE THREAD

**Issue by renmada** [zhuchenxv/AutoFIS#6]

**Comment by zhuchenxv** [comment]
不是，我们用的是criteo 7天的数据，用的是这个链接https://github.com/Atomu2014/Ads-RecSys-Datasets开源得到的数据集。

**Comment by renmada** [comment]
> https://github.com/Atomu2014/Ads-RecSys-Datasets

![image](https://user-images.githubusercontent.com/43545086/145784436-93bf8be7-ace3-40d2-8e32-d919a6dfbdeb.png)
是这个criteo-8d吗？

**Comment by zhuchenxv** [comment]
对，是这个

**Comment by renmada** [comment]
最近在复现Feature Generation by Convolutional Neural Network for Click-Through Rate Prediction。
看到一作与autofis是同一个人，请教几个问题

1. fcnn的criteo也是这个数据吗
2. 我用criteo训练，测试集上达不到0.8022的auc。除了论文里提供的超参，能否告知其他的训练细节，比如learning rate decay；dnn的每一层是否也有batch norm等

**Comment by zhuchenxv** [comment]
FGCNN这个工作我没有参与，我是autofis的另一个共一，这两个问题你可以发邮件去问问FGCNN的作者
