### ISSUE TITLE
Can AutoDeepFM model train numeric data (normalized, not binning)?

### ISSUE THREAD

**Issue by ghost** [zhuchenxv/AutoFIS#7]
Can AutoDeepFM model train numeric data (normalized, not binning)?

**Comment by SeunghyunYoo** [comment]
and also is it possible to train using data configured numeric part and one-hot encoded part like [0.1245, 0, 0, 1, 1, 0, 0]?

**Comment by zhuchenxv** [comment]
For numeric data, you can transforme it into categorical form by bucketing, which is a common way for CTR prediction.
